// export const GET_SCHOOL_ORDERS_REQUEST = 'GET_SCHOOL_ORDERS_REQUEST'
// export const GET_SCHOOL_ORDERS_SUCCESS = 'GET_SCHOOL_ORDERS_SUCCESS'
// export const GET_SCHOOL_ORDERS_ERROR = 'GET_SCHOOL_ORDERS_ERROR'
// export const ORDERS_CHANGE_PAGE = 'ORDERS_CHANGE_PAGE'
